# Generated by Django 3.1.5 on 2021-01-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
